schema_version: 20180708
name: flow
version: 0.0.167
runtime: java8
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.70
run_image: fnproject/fn-java-fdk:jdk9-1.0.70
cmd: com.example.vista.VistaFlow::handleRequest
format: http-stream
timeout: 120
triggers:
- name: flow
  type: http
  source: /flow
