schema_version: 20180708
name: post-slack
version: 0.0.142
runtime: java8
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.74
run_image: fnproject/fn-java-fdk:jdk9-1.0.74
cmd: com.example.vista.PostToSlack::postToSlack
format: http-stream
memory: 256
timeout: 30
idle_timeout: 60
triggers:
- name: post-slack
  type: http
  source: /post-slack
